# Generated by Django 2.2.6 on 2019-10-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20191031_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='db',
            new_name='list_table',
        ),
    ]
