# Generated by Django 2.2.6 on 2019-10-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20191031_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list_table',
            new_name='table',
        ),
    ]
