# Generated by Django 2.2.6 on 2019-10-31 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20191031_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 13, 9, 43, 424763, tzinfo=utc)),
        ),
    ]
