# Generated by Django 2.2.6 on 2019-10-31 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 13, 10, 6, 797475, tzinfo=utc)),
        ),
    ]
