# Generated by Django 2.2.6 on 2019-10-31 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20191031_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 13, 11, 13, 800070, tzinfo=utc)),
        ),
    ]
