# Generated by Django 2.2.6 on 2019-10-31 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20191031_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime(2019, 10, 31, 13, 15, 7, 478494, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='table',
        ),
    ]
