# Generated by Django 2.2.6 on 2019-10-31 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20191031_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_todo',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 13, 15, 17, 141745, tzinfo=utc)),
        ),
    ]
