# Generated by Django 2.2.6 on 2019-10-31 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20191031_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_todo',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 14, 33, 59, 313707, tzinfo=utc)),
        ),
    ]
