# Generated by Django 2.2.6 on 2019-10-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_auto_20191031_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_todo',
            name='date_created',
        ),
    ]
